stages:
  - build

services:
  - docker:dind
variables:
  DOCKER_IMAGE: reber56/sertifika


docker_build:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_HUB_TOKEN
  script:
#    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE:latest
#    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - echo "Compile complete for reber56/sertifika."
#    tags: 
#        - linuxPc

